export const pages = [
  { path: '/', title: 'Vega Protocol - Futures & Perpetuals DEX | Vega Protocol',
    lighthouse: { performance: 60,accessibility: 100, "best-practices": 90, seo: 85, pwa: 100, } },
  { path: '/key-concepts/', title: 'Key Concepts | Vega Protocol',
    lighthouse: { performance: 60,accessibility: 100, "best-practices": 90, seo: 85, pwa: 100, } },
  { path: '/papers/', title: 'Papers | Vega Protocol',
    lighthouse: { performance: 60,accessibility: 100, "best-practices": 90, seo: 85, pwa: 100, } },
  { path: '/articles/', title: 'Articles & Talks | Vega Protocol',
    lighthouse: { performance: 60,accessibility: 100, "best-practices": 90, seo: 85, pwa: 100, } },
  { path: '/community/', title: 'Community | Vega Protocol',
    lighthouse: { performance: 60,accessibility: 100, "best-practices": 90, seo: 85, pwa: 100, } },
  { path: '/community/contributors', title: 'Contributors | Vega Protocol',
    lighthouse: { performance: 60,accessibility: 100, "best-practices": 90, seo: 85, pwa: 100, } },
  { path: '/community/ambassadors', title: 'Ambassadors | Vega Protocol',
    lighthouse: { performance: 60,accessibility: 100, "best-practices": 90, seo: 85, pwa: 100, } },
  { path: '/wallet', title: 'Wallet | Vega Protocol',
    lighthouse: { performance: 60,accessibility: 100, "best-practices": 90, seo: 85, pwa: 100, } },
  { path: '/governance', title: 'Governance Home | Vega Protocol',
    lighthouse: { performance: 60,accessibility: 100, "best-practices": 90, seo: 85, pwa: 100, } },
  { path: '/market-creation', title: 'Market Creation with Vega | Vega Protocol',
    lighthouse: { performance: 60,accessibility: 100, "best-practices": 90, seo: 85, pwa: 100, } },
  { path: '/builders-club/', title: 'Builders Club | Vega Protocol',
    lighthouse: { performance: 60,accessibility: 100, "best-practices": 90, seo: 85, pwa: 100, } }
]
