export const pages = [
  { path: '/', title: 'Blockchain derivatives | Vega Protocol',
    lighthouse: { performance: 60,accessibility: 100, "best-practices": 90, seo: 85, pwa: 100, } },
  { path: '/key-concepts/', title: 'Key Vega Concepts | Vega Protocol',
    lighthouse: { performance: 60,accessibility: 100, "best-practices": 90, seo: 85, pwa: 100, } },
  { path: '/papers/', title: 'Papers & Research | Vega Protocol',
    lighthouse: { performance: 60,accessibility: 100, "best-practices": 90, seo: 85, pwa: 100, } },
  { path: '/talks/', title: 'Talks | Vega Protocol',
    lighthouse: { performance: 60,accessibility: 100, "best-practices": 90, seo: 85, pwa: 100, } },
  { path: '/develop/', title: 'Develop with Vega | Vega Protocol',
    lighthouse: { performance: 60,accessibility: 100, "best-practices": 90, seo: 85, pwa: 100, } },
  { path: '/use/', title: 'Use the network | Vega Protocol',
    lighthouse: { performance: 60,accessibility: 100, "best-practices": 90, seo: 85, pwa: 100, } },
  { path: '/community/', title: 'Community | Vega Protocol',
    lighthouse: { performance: 60,accessibility: 100, "best-practices": 90, seo: 85, pwa: 100, } },
  { path: '/careers/', title: 'Careers at Vega | Vega Protocol',
    lighthouse: { performance: 60,accessibility: 100, "best-practices": 90, seo: 85, pwa: 100, } },
  { path: '/community/contributors', title: 'Contributors | Vega Protocol',
    lighthouse: { performance: 60,accessibility: 100, "best-practices": 90, seo: 85, pwa: 100, } },
  { path: '/community/ambassadors', title: 'Be a Vega+ Ambassador | Vega Protocol',
    lighthouse: { performance: 60,accessibility: 100, "best-practices": 90, seo: 85, pwa: 100, } },
  { path: '/partners-backers', title: 'Partners & Backers | Vega Protocol',
    lighthouse: { performance: 60,accessibility: 100, "best-practices": 90, seo: 85, pwa: 100, } },
  { path: '/wallet', title: 'Get the Vega Wallet | Vega Protocol',
    lighthouse: { performance: 60,accessibility: 100, "best-practices": 90, seo: 85, pwa: 100, } },
  { path: '/governance', title: 'Governance | Vega Protocol',
    lighthouse: { performance: 60,accessibility: 100, "best-practices": 90, seo: 85, pwa: 100, } }
]
